name: dart_windows_service_support
description: dart to windows service 
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
    sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
    lints: ^2.0.0
    test: ^1.16.0
dependencies:
    ffi: ^2.0.1
    ffigen: ^7.2.0
    path: ^1.8.2
